Modal for links
SolidOS/solid-ui pull request #389
Opened 2021-03-29 10:06 UTC by SharonStrats

This is a modal. 
if you have an array of links [{ label: 'string', link: 'string'}, ... ]
You call createWindow(Dom, listofLinks) and it will return the modal. To display the modal by clicking a button add modal.display = 'block' to the onClickFunction. This has not been tested yet, due to some other technical issues.

I have also created a modalStyle file next to the modal. I think this is how we should do it as we go forward so that the styles are next to the file we are styling when possible. 

TODO: change the styling so that when the user hovers on li the li has a background color.

2021-03-29 15:59 UTC, jeff-zucker requested changes
Haven't finished testing yet, but these changes allow it to compile without errors

Line 8 of modals.ts

  * change ../jss to ../lib/jss

Line 1 modalsStyles.ts

   * change ** to /*

2021-04-02 11:33 UTC, angelo-v commented
Cool. Could you please add unit tests and also stories to storybook?

2023-04-17 12:05 UTC, timbl commented
Is this a modal in the sense that it block all interaction for the user until the choice has been made?   If so then I would prefer that it is not. It should allow the user to work on other things while the choice has not been made yet.  Maybe it already does.

See https://www.w3.org/DesignIssues/UserInterface.html#modals
Also good to pass the function a DOM element near or under ot on top of which to make the pop-up so the choice doesn't get lost in the wrong part of the UI.

2023-04-17 13:35 UTC, TallTed reviewed
clarity changes to comments, and adding some `//` comment markers to lines without them in larger current `/* ... */` comment blocks (so if the `/* ... */` wrappers around the code are removed, these comment lines don't break the build)

2023-04-17 13:35 UTC, TallTed commented on src/widgets/modals.ts
> +even if the user doesn't click close
```suggestion
// Window click handler so that the modal will close
// even if the user doesn't click close.
```

2023-04-17 13:35 UTC, TallTed commented on src/widgets/modals.ts
> +// When the user clicks the button, open the modal
```suggestion
// Two functions that need to be implemented to use the modal.
// When the user clicks the button, open the modal.
```

2023-04-17 13:35 UTC, TallTed commented on src/widgets/modals.ts
> +// When the user clicks anywhere outside of the modal, close it
```suggestion
// When the user clicks anywhere outside of the modal, close it.
```

2026-03-25 23:23 UTC, SharonStrats commented on src/widgets/modals.ts
> +}
done

2026-04-02 14:43 UTC, timea-solid commented
What would help here is a screenshot of how the modal looks.

2026-04-02 17:24 UTC, TallTed commented on src/acl/access-groups.ts
>          ' Hint: try dropping a WebID profile URI, a vcard:Group URI, or a web app origin.' +
It seems odd to combine (`+`) lines of backtick-wrapped text with lines of apostrophe-wrapped text. Given that line 267 is being changed from the former to the latter by this PR, it seems likely that line 266 (now backtick-wrapped) should be changed to match lines 267-268 (now apostrophe-wrapped).

2026-05-04 23:43 UTC, SharonStrats commented
I don't think we really need this anymore. if we do we can recreate in a web component.

2026-05-04 23:43 UTC, closed without merging